import "dotenv/config";
import { runAutonomousGlyphCycle } from "../../src/lib/cycle/orchestrator";
import { prisma } from "../../src/lib/prisma";

async function main() {
  const targetAsset = process.argv[2] || "AAPL";
  const agentIdentifier = process.env.GLYPH_AGENT_ID || "3";

  console.log("===============================================================");
  console.log(`🚀 TRIGGERING 1X AUTONOMOUS TRADE DECISION`);
  console.log(`🎯 Target Asset: ${targetAsset}`);
  console.log(`🤖 Agent ID:     #${agentIdentifier}`);
  console.log("===============================================================\n");

  const result = await runAutonomousGlyphCycle({
    targetAsset,
    agentIdentifier,
  });

  console.log("\n===============================================================");
  console.log("📊 EXECUTION SUMMARY RESULT");
  console.log("===============================================================");
  console.log(`- Success:          ${result.success}`);
  console.log(`- Asset Analyzed:   ${result.targetAsset}`);
  console.log(`- Decision Action:  ${result.decisionResult.action}`);
  console.log(`- Conviction:       ${result.decisionResult.conviction}%`);
  console.log(`- Policy Result:    ${result.decisionResult.policyResult}`);
  if (result.decisionResult.policyRejectReason) {
    console.log(`- Policy Reason:    ${result.decisionResult.policyRejectReason}`);
  }
  if (result.decisionResult.tradeId) {
    console.log(`- Trade ID:         ${result.decisionResult.tradeId}`);
    console.log(`- Trade Number:     ${result.decisionResult.tradeNumber}`);
  }
  if (result.decisionResult.transactionHash) {
    console.log(`- Tx Hash:          ${result.decisionResult.transactionHash}`);
    console.log(`- Explorer URL:     ${result.decisionResult.explorerUrl}`);
  }
  console.log(`- Execution Time:   ${result.executionDurationMs} ms`);
  console.log("===============================================================");

  // Output the full structured thesis
  console.log("\n📝 STRUCTURED THESIS GENERATED BY GLYPH BRAIN:");
  console.log(JSON.stringify(result.decisionResult.decision.thesis, null, 2));
}

main()
  .catch((err) => {
    console.error("\n❌ Execution failed:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
